from typing import Any, Dict, List

from logger import logger
from app.core.vector_db import soc_vdb


# =====================================================================
# HISTORICAL KNOWLEDGE DATASET
# =====================================================================

HISTORICAL_PATTERNS: List[Dict[str, Any]] = [

    # =================================================================
    # DOC 1 — PORT SCAN / RECONNAISSANCE
    # =================================================================

    {
        "key": (
            "External TCP reconnaissance targeting internal SSH, HTTP, "
            "HTTPS, and RDP services across corporate DMZ range."
        ),

        "value": (
            "Historically, this pattern was confirmed as a True Positive "
            "when an unauthorized external host systematically probed "
            "internal ports (22, 80, 443, 3389); blocking the source IP at "
            "the perimeter firewall successfully contained the threat. "
            "Conversely, a similar pattern was classified as a False Positive "
            "when the source matched the authorized internal vulnerability scanner "
            "(192.168.1.50) operating during a scheduled compliance scan window."
        )
    },

    # =================================================================
    # DOC 2 — SQL INJECTION
    # =================================================================

    {
        "key": (
            "External HTTPS requests targeting web application authentication "
            "or data query endpoints containing SQL injection keywords like "
            "UNION SELECT, OR 1=1, or SQL comment characters."
        ),

        "value": (
            "Historically, this behavior was marked as a True Positive when "
            "an attacker attempted automated SQL injection against the primary web "
            "app gateway (10.0.0.10) to access underlying database schema; "
            "blocking the IP at WAF and dropping the request mitigated the issue. "
            "It was confirmed as a False Positive during internal penetration "
            "testing when explicit authorization change tickets were filed."
        )
    },

    # =================================================================
    # DOC 3 — BRUTE FORCE / CREDENTIAL ATTACK
    # =================================================================

    {
        "key": (
            "High-volume authentication failures over SSH or RDP (exceeding "
            "20 failures within 60 seconds) targeting domain accounts or "
            "critical infrastructure servers."
        ),

        "value": (
            "Historically, this pattern was verified as a True Positive when "
            "an external IP conducted a password-spraying campaign against "
            "remote access gateways; enforcing account lockout and blocking "
            "the IP prevented unauthorized access. A False Positive instance "
            "occurred when a legitimate service account credential expired, "
            "causing an automated backup script to trigger repeated login failures."
        )
    },

    # =================================================================
    # DOC 4 — WEB SCANNING / DIRECTORY BRUTE FORCE
    # =================================================================

    {
        "key": (
            "High-frequency HTTPS directory enumeration and path probing targeting "
            "administrative control panels, environment files (.env), or "
            "backup archives."
        ),

        "value": (
            "Historically, this activity was confirmed as a True Positive when "
            "an external threat actor ran tools like Gobuster/Dirbuster against "
            "production web servers; adding dynamic rate-limiting and blocking "
            "the IP stopped the reconnaissance. It was recorded as a False Positive "
            "when generated by approved Web Application Firewall (WAF) health-check probes."
        )
    },

    # =================================================================
    # DOC 5 — DNS TUNNELING
    # =================================================================

    {
        "key": (
            "An internal endpoint producing anomalous high-volume DNS requests with "
            "unusually long subdomains, TXT record queries, or high-entropy "
            "base64-encoded payloads."
        ),

        "value": (
            "Historically, this was confirmed as a True Positive when a malware "
            "infection used DNS tunneling (e.g., Iodine/DNScat2) for Command "
            "& Control (C2) communications; isolating the workstation and sinkholing "
            "the domain resolved the threat. A False Positive occurred when a "
            "legacy security agent transmitted system diagnostic metrics via encoded DNS queries."
        )
    },

    # =================================================================
    # DOC 6 — MALWARE / RANSOMWARE
    # =================================================================

    {
        "key": (
            "Internal workstation exhibiting rapid mass file encryption, abnormal "
            "shadow copy deletion commands (vssadmin), or bulk SMB write operations "
            "targeting critical network shares."
        ),

        "value": (
            "Historically, this critical pattern was a True Positive indicating "
            "active ransomware execution; automated EDR containment isolated the host, "
            "preventing lateral movement to the Production DB (10.0.0.5). "
            "False Positive incidents were linked to administrative bulk-archiving "
            "tasks executing unannounced data compression routines."
        )
    },

    # =================================================================
    # DOC 7 — PHISHING / CREDENTIAL HARVESTING
    # =================================================================

    {
        "key": (
            "Inbound corporate email containing obfuscated links, suspicious "
            "attachments (e.g., ISO, ZIP, macro-enabled XLSM), or newly registered "
            "lookalike domain URIs."
        ),

        "value": (
            "Historically, this pattern was verified as a True Positive when "
            "users received credential-harvesting emails mimicking the corporate "
            "SSO portal; purging emails from mailboxes and blocking domains averted "
            "compromise. It was classified as a False Positive when originating from "
            "the official Security Awareness Training simulated phishing vendor."
        )
    },

    # =================================================================
    # DOC 8 — CLOUD IAM / ANOMALOUS PRIVILEGE ESCALATION
    # =================================================================

    {
        "key": (
            "Unusual administrative cloud API calls originating from unapproved "
            "IP addresses, including creating administrative users, modifying IAM "
            "roles, or disabling audit logging (CloudTrail)."
        ),

        "value": (
            "Historically, this was a True Positive representing compromised API "
            "access keys being used to establish persistence; revoking the keys and "
            "deleting unauthorized IAM policies contained the incident. A False "
            "Positive occurred when DevOps engineers deployed Terraform templates "
            "during an emergency maintenance window without prior ticket logging."
        )
    },

    # =================================================================
    # DOC 9 — DATA EXFILTRATION
    # =================================================================

    {
        "key": (
            "Large outbound HTTPS data transfers (exceeding 1GB) initiated by "
            "an internal endpoint targeting unapproved cloud storage or external IP "
            "addresses outside approved destinations."
        ),

        "value": (
            "Historically, this was confirmed as a True Positive when an infected "
            "endpoint transferred sensitive databases to an external C2 server; "
            "network isolation and firewall blocking mitigated data loss. "
            "A False Positive was identified when FinanceServer01 transferred "
            "approved encrypted backups to the authorized AWS destination (185.199.108.153)."
        )
    },

    # =================================================================
    # DOC 10 — LATERAL MOVEMENT / RDP - SMB EXPLOITATION
    # =================================================================

    {
        "key": (
            "Unauthorized internal network connection attempts over RPC or SMB "
            "from user LAN segments (172.16.x.x) directly targeting the Domain "
            "Controller (10.0.0.2)."
        ),

        "value": (
            "Historically, this was verified as a True Positive when an attacker "
            "attempted lateral movement using PSExec/WMI after gaining an initial "
            "foothold; blocking traffic per network segmentation policy stopped "
            "the escalation. It was a False Positive when an authorized admin used "
            "a non-standard workstation instead of the designated Jump Box (172.16.1.100)."
        )
    },
]


# =====================================================================
# INGESTION
# =====================================================================

def run_ingestion(clear_existing: bool = True) -> None:
    """
    Insert historical knowledge into ChromaDB.

    Logical record structure:

        id
        key
        value

    ChromaDB mapping:

        id    -> ids
        key   -> documents
        value -> metadata["value"]

    The metadata contains ONLY the value.
    No additional metadata fields are created.
    """

    logger.info("🚀 Starting SOC Knowledge Ingestion...")

    # -----------------------------------------------------------------
    # CLEAR OLD DATA
    # -----------------------------------------------------------------

    if clear_existing:
        logger.info("🧹 Clearing existing ChromaDB records...")
        soc_vdb.clear_all()

    # -----------------------------------------------------------------
    # INSERT RECORDS
    # -----------------------------------------------------------------

    for index, entry in enumerate(
        HISTORICAL_PATTERNS,
        start=1
    ):

        try:

            # ---------------------------------------------------------
            # ID
            # ---------------------------------------------------------

            record_id = f"pattern_{index}"

            # ---------------------------------------------------------
            # KEY
            # This is the text ChromaDB embeds and searches against.
            # ---------------------------------------------------------

            key = entry["key"]

            # ---------------------------------------------------------
            # VALUE
            # This is the historical knowledge returned after search.
            # ---------------------------------------------------------

            value = entry["value"]

            # ---------------------------------------------------------
            # CHROMA INSERT
            #
            # Logical structure:
            #
            # {
            #     "id": record_id,
            #     "key": key,
            #     "value": value
            # }
            #
            # ChromaDB internally represents this as:
            #
            # ids       -> record_id
            # documents -> key
            # metadata  -> value
            #
            # There are NO other metadata fields.
            # ---------------------------------------------------------

            soc_vdb.collection.add(
                ids=[record_id],
                documents=[key],
                metadatas=[
                    {
                        "value": value
                    }
                ],
            )

            logger.info(
                f"✅ Indexed record "
                f"{index}/{len(HISTORICAL_PATTERNS)} "
                f"| id={record_id}"
            )

        except Exception as err:

            logger.error(
                f"❌ Failed to ingest record "
                f"{index}: {err}"
            )

            raise

    # -----------------------------------------------------------------
    # FINAL COUNT
    # -----------------------------------------------------------------

    total_docs = soc_vdb.get_total_documents()

    logger.info(
        f"✨ Ingestion complete. "
        f"Total records in Vector DB: {total_docs}"
    )


# =====================================================================
# MAIN
# =====================================================================

if __name__ == "__main__":

    run_ingestion(
        clear_existing=True
    )